version: '3.1'

services:

  app:
    build: .
    volumes:
      - ./:/src/go
      - $GOPATH/pkg/mod:/go/pkg/mod
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
    working_dir: /src/go
    command: go run main.go
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    command: elasticsearch -Ehttp.cors.allow-origin="*" -Ehttp.cors.enabled=true -Ehttp.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization -Ehttp.cors.allow-credentials=true -Elogger.level=WARN

  kibana:
    image:  docker.elastic.co/kibana/kibana:6.3.2
    environment:
      - LOGGING_QUIET=true
      - LOGGING_SILENT=true
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200